version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: capstone_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: capstone
    networks:
      - newnetwork

      

networks:
  newnetwork:
